"""initial

Revision ID: cf214ee0de73
Revises:
Create Date: 2026-04-18 11:01:57.043267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf214ee0de73"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column(
            "model", sa.SmallInteger(), nullable=False
        ),
        sa.Column(
            "action", sa.SmallInteger(), nullable=False
        ),
        sa.Column("instance_id", sa.String(length=255), nullable=False),
        sa.Column("executor_id", sa.String(length=255), nullable=False),
        sa.Column(
            "before", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "after", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "executor_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(
                always=False,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_logs_action"), "logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_logs_created_at"), "logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_logs_executor_id"), "logs", ["executor_id"], unique=False
    )
    op.create_index(op.f("ix_logs_id"), "logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_logs_instance_id"), "logs", ["instance_id"], unique=False
    )
    op.create_index(op.f("ix_logs_model"), "logs", ["model"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_logs_model"), table_name="logs")
    op.drop_index(op.f("ix_logs_instance_id"), table_name="logs")
    op.drop_index(op.f("ix_logs_id"), table_name="logs")
    op.drop_index(op.f("ix_logs_executor_id"), table_name="logs")
    op.drop_index(op.f("ix_logs_created_at"), table_name="logs")
    op.drop_index(op.f("ix_logs_action"), table_name="logs")
    op.drop_table("logs")
    # ### end Alembic commands ###
