services:

  db:
    image: postgres:15
    container_name: ${PROJECT_NAME}_db
    networks:
      - local
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: ${PROJECT_NAME}_pgbouncer
    networks:
      - local
    restart: always
    expose:
      - "6432"
    env_file:
      - .env
    environment:
      - POSTGRESQL_HOST=hr_chat_db
      - POSTGRESQL_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - PGBOUNCER_PORT=6432
      - PGBOUNCER_ADMIN_USERS=${DB_USER}
      - PGBOUNCER_STATS_USERS=${DB_USER}
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h 127.0.0.1 -p 6432 -U ${DB_USER} || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_started

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ${PROJECT_NAME}_app
    entrypoint: /scripts/entrypoint.sh
    networks:
      - local
    ports:
      - "127.0.0.1:8021:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=${PROJECT_NAME}_pgbouncer
      - DB_PORT=6432
    depends_on:
      - redis
      - db


  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_admin
    entrypoint: ./admin/entrypoint.sh
    networks:
      - local
    ports:
      - "127.0.0.1:8066:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=${PROJECT_NAME}_pgbouncer
      - DB_PORT=6432

volumes:
  postgres_data: { }
  redis_data: { }


networks:
  local:
    name: hr_shared_net
    external: true