services:
  redis:
    image: redis:7-alpine
    container_name: ${CONTAINER_PREFIX:-face_detection}_redis
    restart: unless-stopped
    networks:
      - local
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ${CONTAINER_PREFIX:-face_detection}_qdrant
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - local
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ${CONTAINER_PREFIX:-face_detection}_app
    image: ${CONTAINER_PREFIX:-face_detection}_app_image:latest
    entrypoint: /scripts/entrypoint.sh
    networks:
      - local
    ports:
      - "${APP_BIND_IP:-127.0.0.1}:${APP_PORT:-8080}:8000"
    env_file:
      - .env
    volumes:
      - insightface_data:/root/.insightface
      - face_images:/app/media/faces
    depends_on:
      redis:
        condition: service_healthy
      qdrant:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s



volumes:
  redis_data: { }
  qdrant_data: { }
  insightface_data: { }
  face_images: { }


networks:
  local:
    name: semantic_search
    external: false
