[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:fastapi]
command=gunicorn -c gunicorn_conf.py main:app
directory=/app
autostart=true
autorestart=true
startsecs=5
startretries=3
stopwaitsecs=30
stopasgroup=true
killasgroup=true
priority=100
stdout_logfile=/var/log/app/gunicorn_access.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/var/log/app/gunicorn_error.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
