"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import log_pb2 as _log_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class LogServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> LogServiceAsyncStub: ...
    CreateLog: _grpc.UnaryUnaryMultiCallable[_log_pb2.LogCreateRequest, _log_pb2.LogResponse]

@_typing.type_check_only
class LogServiceAsyncStub(LogServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    CreateLog: _aio.UnaryUnaryMultiCallable[_log_pb2.LogCreateRequest, _log_pb2.LogResponse]  # type: ignore[assignment]

class LogServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def CreateLog(
        self,
        request: _log_pb2.LogCreateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_log_pb2.LogResponse, _abc.Awaitable[_log_pb2.LogResponse]]: ...

def add_LogServiceServicer_to_server(servicer: LogServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
