"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class LogCreateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODEL_FIELD_NUMBER: _builtins.int
    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    EXECUTOR_FIELD_NUMBER: _builtins.int
    COMMENT_FIELD_NUMBER: _builtins.int
    BEFORE_FIELD_NUMBER: _builtins.int
    AFTER_FIELD_NUMBER: _builtins.int
    model: _builtins.int
    instance_id: _builtins.str
    executor: _builtins.str
    comment: _builtins.str
    @_builtins.property
    def before(self) -> _struct_pb2.Struct: ...
    @_builtins.property
    def after(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        model: _builtins.int = ...,
        instance_id: _builtins.str = ...,
        executor: _builtins.str = ...,
        comment: _builtins.str = ...,
        before: _struct_pb2.Struct | None = ...,
        after: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["after", b"after", "before", b"before"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after", b"after", "before", b"before", "comment", b"comment", "executor", b"executor", "instance_id", b"instance_id", "model", b"model"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogCreateRequest: _TypeAlias = LogCreateRequest  # noqa: Y015

@_typing.final
class LogResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    EXECUTOR_FIELD_NUMBER: _builtins.int
    COMMENT_FIELD_NUMBER: _builtins.int
    BEFORE_FIELD_NUMBER: _builtins.int
    AFTER_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    model: _builtins.int
    instance_id: _builtins.str
    executor: _builtins.str
    comment: _builtins.str
    created_at: _builtins.str
    @_builtins.property
    def before(self) -> _struct_pb2.Struct: ...
    @_builtins.property
    def after(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        model: _builtins.int = ...,
        instance_id: _builtins.str = ...,
        executor: _builtins.str = ...,
        comment: _builtins.str = ...,
        before: _struct_pb2.Struct | None = ...,
        after: _struct_pb2.Struct | None = ...,
        created_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["after", b"after", "before", b"before"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after", b"after", "before", b"before", "comment", b"comment", "created_at", b"created_at", "executor", b"executor", "id", b"id", "instance_id", b"instance_id", "model", b"model"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogResponse: _TypeAlias = LogResponse  # noqa: Y015
